services:
  bot:
    image: "stirbot:${TAG-latest}"
    env_file:
      - .env
    build:
      context: .
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - app

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - app
    volumes:
      - app-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: /bin/sh -c
            'if [ -n "$REDIS_PASSWORD" ];
              then redis-server --port "$REDIS_PORT" --requirepass "$REDIS_PASSWORD";
            else redis-server --port "$REDIS_PORT"; fi'
    networks:
      - app
    volumes:
      - redis-data:/data

networks:
  app:

volumes:
  app-db-data: {}
  redis-data: {}
