services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace
      # т.к пути в venv'е - абсолютные, то при переносе на основную ОС он становится бесполезным поэтому он изолирован
      - venv:/workspace/.venv
    env_file:
      - ../.env
    environment:
      # необходимо для того, что бы pre-commit не скачивал заново хуки после остановки контейнера
      - PRE_COMMIT_HOME=/workspace/.venv/pre-commit
      - PYTHONPATH=/workspace
    command: sleep infinity

  db:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/pgdata
    env_file:
      - ../.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7-alpine
    env_file:
      - ../.env
    command: /bin/sh -c
            'if [ -n "$${REDIS_PASSWORD}" ];
              then redis-server --port "$${REDIS_PORT}" --requirepass "$${REDIS_PASSWORD}";
            else redis-server --port "$${REDIS_PORT}"; fi'
    volumes:
      - redis-data:/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 7731
    ports:
      - 7731:7731
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  venv:
  postgres-data:
  pgadmin:
  redis-data:
